baseURL = "https://benhattem.nl/"
languageCode = "en-us"
title = "benhattem.nl"
theme = "hugo-m10c-benh"

[menus]
  [[menu.main]]
    identifier = "home"
    name = 'Home'
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  author = "Ben Hattem"
  description = "Ben's personal website."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/bh1428"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/benhattem/"
  [params.github]
    bh1428_aoc_2025 = "https://github.com/bh1428/advent-of-code/blob/main/2025/"

[taxonomies]
  tag = 'tags'
